### ISSUE TITLE
`@protected` keyword set to a string

### ISSUE THREAD

**Issue by timothee-haudebourg** [digitalbazaar/cit-context#7]
Hi, I'm unable to process the `cit-v1` context because a `@protected` keyword is set to a string, and not a boolean value here:
https://github.com/digitalbazaar/cit-context/blob/8df2a814dadc56dc53fee5d55787418348d997d6/contexts/cit-v1.jsonld#L3

**Comment by davidlehn** [comment]
Fixed in 2.0.1.
